language: elixir
elixir:
  - '1.7'
  - '1.8'
otp_release:
  - '21.1'
  - '21.2'

# Build only if the type of the job is not a push
if: type != push

# Only clone the current commit
git:
  depth: 1

sudo: false

addons:
  postgresql: '9.6'

env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
    - MIX_ENV=test

install:
  - mix do local.hex --force, local.rebar --force || echo "WARNING! Unable to update hex or rebar"
  - mix deps.get
  - mix deps.compile
  - npm install -g elm-format elm-test
  - pushd apps/tag_editor/assets
  - npm install
  - popd

script:
  - mix format --check-formatted
  - for f in $(mix format --check-formatted 2>&1 | cut -s -d' ' -f4- | grep -E '^.+\.exs?$'); do echo $f; cat $f | mix format - | diff $f -; done
  - mix compile --warnings-as-errors --all-warnings
  - mix ecto.create
  - mix ecto.migrate
  - mix coveralls.travis -u
  - mix credo --strict
  - travis_wait mix dialyzer --halt-exit-status
  - pushd apps/tag_editor/assets/
  - travis_wait elm-test
  - find elm-src -name '*.elm' -exec elm-format {} --validate \;
  - popd

# Cache as much as possible
cache:
  directories:
    - deps
    - _build
    - apps/tag_editor/assets/tests/elm-stuff

# Trigger our discord webhook
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
