language: elixir
elixir:
  - '1.6'
  - '1.7'
otp_release:
  - '20.3'
  - '21.0'
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
    - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force || echo "WARNING! Unable to update hex or rebar"
  - mix deps.get
  - mix deps.compile
script:
  - mix compile --warnings-as-errors --all-warnings
  - mix format --check-formatted
  - mix ecto.create
  - mix ecto.migrate
  - mix coveralls.travis -u
  - mix credo --strict
  - mix dialyzer
