use Mix.Config

config :common, :tag_translations, %{
  "Animation - Modified" => ["Animation"],
  "Animation" => ["Animation"],
  "Armour - Shields" => ["Items.Armour.Shields"],
  "Armour & Shields" => ["Items.Armour"],
  "Armour" => ["Items.Armour"],
  "Audio" => ["Audio"],
  "Balance" => ["Gameplay.Balance"],
  "Body models" => ["Characters.Body", "Graphics.Models"],
  "Body, Face, and Hair" => ["Characters.Body", "Graphics.Models"],
  "Body" => ["Characters.Body"],
  "Bodyslide, OutfitStudio, and TexBlend Presets" => [
    "Characters.Body",
    "Graphics.Models",
    "Tools.CBBE"
  ],
  "Books" => ["Items.Books"],
  "Bug Fixes" => ["Patches.Bug_Fixes"],
  "Buildings" => ["World.Buildings"],
  "Character Presets" => ["Characters"],
  "Chargen" => ["Characters"],
  "Cheating" => ["Misc.Unrealistic"],
  "Cheats and God items" => ["Gameplay.Cheats_and_God_items"],
  "Companions - Creatures" => ["Characters.NPC.Followers", "Creatures"],
  "Companions" => ["Characters.NPC.Followers"],
  "Companions/Followers" => ["Characters.NPC.Followers"],
  "Creatures - Rideable" => ["Creatures.Mounts"],
  "Dungeons - New" => ["World.Locations.Dungeons"],
  "Dungeons - Vanilla" => ["World.Locations.Dungeons"],
  "Enderal: Armour" => ["World.Setting.Enderal"],
  "Enderal: Bug Fixes" => ["World.Setting.Enderal"],
  "Enderal: Cheats and God items" => ["World.Setting.Enderal"],
  "Enderal: Miscellaneous" => ["Misc", "World.Setting.Enderal"],
  "Enderal: Player Homes" => ["World.Buildings.Player_Homes", "World.Setting.Enderal"],
  "Enderal: Spells & Enchantments" => ["Magic", "World.Setting.Enderal"],
  "Enderal: User Interface" => ["Gameplay.User_Interface", "World.Setting.Enderal"],
  "Enderal: Weapons" => ["Items.Weapons"],
  "Environment - Other" => ["World.Environment"],
  "Face models" => ["Graphics.Models"],
  "Fair and balanced" => ["Gameplay.Balance"],
  "Gameplay Effects/Changes" => ["Gameplay.Effects_and_Changes"],
  "Guilds / Factions" => ["Faction"],
  "Items - Leveled" => ["Items"],
  "Items and Objects - Player" => ["Items"],
  "Items and Objects - World" => ["Items"],
  "Locations - New" => ["World.Locations"],
  "Locations - Player-Owned" => ["World.Locations.Player_Owned"],
  "Locations - Vanilla" => ["World.Locations"],
  "Modder's Resource" => ["Misc.Resources"],
  "Modders Resources and Tutorials" => ["Misc.Tutorials"],
  "Models and Textures" => ["Graphics"],
  "New Lands" => ["World.Setting"],
  "Non-Playable Resource" => ["Misc.Resources"],
  "NPC" => ["Characters.NPC"],
  "Nudity" => ["Not_Safe_For_Work.Nudity"],
  "Overhauls" => ["MI.Overhaul"],
  "Quests" => ["World.Quests"],
  "RaceMenu preset" => ["Characters"],
  "Races - Modified" => ["Characters.Races"],
  "Related to horses" => ["Creatures.Mounts"],
  "Save Games" => ["Gameplay.Save_Games"],
  "Seraphim Bodybase" => ["Characters.Body"],
  "SevenBase Bodybase" => ["Characters.Body"],
  "Sexualised content" => ["Not_Safe_For_Work.Nudity"],
  "Tutorials for Modders" => ["Misc.Tutorials"],
  "UNP Bodybase" => ["Characters.Body"],
  "Utilities for Modders" => ["Misc.Utilities"],
  "Utilities" => ["Misc.Utilities"],
  "Video" => ["Misc.Videos_and_Trailers"]
}
